export const NOTICE_ERROR_CODES = {
  // Authorization
  FORBIDDEN: 'ERR_FORBIDDEN',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  TENANT_MISMATCH: 'ERR_TENANT_MISMATCH',

  // Validation
  VALIDATION_ERROR: 'ERR_VALIDATION_ERROR',
  INVALID_TARGET: 'ERR_INVALID_TARGET',
  INVALID_STATE_TRANSITION: 'ERR_INVALID_STATE_TRANSITION',
  DUE_DATE_BEFORE_PUBLISH: 'ERR_DUE_DATE_BEFORE_PUBLISH',
  EXPIRY_BEFORE_PUBLISH: 'ERR_EXPIRY_BEFORE_PUBLISH',

  // Business Rules
  DUPLICATE_NOTICE: 'ERR_DUPLICATE_NOTICE',
  PIN_LIMIT_EXCEEDED: 'ERR_PIN_LIMIT_EXCEEDED',
  ALREADY_PINNED: 'ERR_ALREADY_PINNED',
  NOT_PINNED: 'ERR_NOT_PINNED',
  CANNOT_MODIFY_PUBLISHED: 'ERR_CANNOT_MODIFY_PUBLISHED',
  CANNOT_DELETE_PUBLISHED: 'ERR_CANNOT_DELETE_PUBLISHED',
  COMMENTS_DISABLED: 'ERR_COMMENTS_DISABLED',
  COMMENT_EDIT_WINDOW_EXPIRED: 'ERR_COMMENT_EDIT_WINDOW_EXPIRED',
  ACKNOWLEDGMENT_NOT_REQUIRED: 'ERR_ACKNOWLEDGMENT_NOT_REQUIRED',
  ALREADY_ACKNOWLEDGED: 'ERR_ALREADY_ACKNOWLEDGED',
  ACKNOWLEDGMENT_DEADLINE_PASSED: 'ERR_ACKNOWLEDGMENT_DEADLINE_PASSED',
  TEACHER_SCOPE_VIOLATION: 'ERR_TEACHER_SCOPE_VIOLATION',

  // Resources
  NOTICE_NOT_FOUND: 'ERR_NOTICE_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'ERR_CATEGORY_NOT_FOUND',
  ATTACHMENT_NOT_FOUND: 'ERR_ATTACHMENT_NOT_FOUND',
  COMMENT_NOT_FOUND: 'ERR_COMMENT_NOT_FOUND',

  // File Upload
  FILE_TOO_LARGE: 'ERR_FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'ERR_INVALID_FILE_TYPE',
  FILE_UPLOAD_FAILED: 'ERR_FILE_UPLOAD_FAILED',

  // General
  INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
} as const;