export const NOTIFICATION_EVENT_TYPES = {
  // Academic
  ASSIGNMENT_PUBLISHED: 'ASSIGNMENT_PUBLISHED',
  ASSIGNMENT_UPDATED: 'ASSIGNMENT_UPDATED',
  ASSIGNMENT_DUE_SOON: 'ASSIGNMENT_DUE_SOON',
  ASSIGNMENT_GRADED: 'ASSIGNMENT_GRADED',
  EXAM_CREATED: 'EXAM_CREATED',
  EXAM_UPDATED: 'EXAM_UPDATED',
  EXAM_CANCELLED: 'EXAM_CANCELLED',
  RESULT_PUBLISHED: 'RESULT_PUBLISHED',
  RESULT_UPDATED: 'RESULT_UPDATED',

  // Attendance
  STUDENT_MARKED_ABSENT: 'STUDENT_MARKED_ABSENT',
  ATTENDANCE_CORRECTION_APPROVED: 'ATTENDANCE_CORRECTION_APPROVED',
  ATTENDANCE_CORRECTION_REJECTED: 'ATTENDANCE_CORRECTION_REJECTED',
  TEACHER_MARKED_ABSENT: 'TEACHER_MARKED_ABSENT',

  // Fees
  FEE_ASSIGNED: 'FEE_ASSIGNED',
  FEE_DUE_SOON: 'FEE_DUE_SOON',
  FEE_OVERDUE: 'FEE_OVERDUE',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  REFUND_PROCESSED: 'REFUND_PROCESSED',

  // Leave
  LEAVE_SUBMITTED: 'LEAVE_SUBMITTED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  LEAVE_WITHDRAWN: 'LEAVE_WITHDRAWN',

  // Notices
  NOTICE_PUBLISHED: 'NOTICE_PUBLISHED',
  CIRCULAR_PUBLISHED: 'CIRCULAR_PUBLISHED',
  NOTICE_UPDATED: 'NOTICE_UPDATED',
  NOTICE_EXPIRING: 'NOTICE_EXPIRING',

  // Timetable
  TIMETABLE_PUBLISHED: 'TIMETABLE_PUBLISHED',
  TIMETABLE_UPDATED: 'TIMETABLE_UPDATED',
  CLASS_CANCELLED: 'CLASS_CANCELLED',

  // System & Security
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  SECURITY_ALERT: 'SECURITY_ALERT',
  SYSTEM_ANNOUNCEMENT: 'SYSTEM_ANNOUNCEMENT',
} as const;

export type NotificationEventType =
  (typeof NOTIFICATION_EVENT_TYPES)[keyof typeof NOTIFICATION_EVENT_TYPES];

export const NOTIFICATION_ERROR_CODES = {
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  UNAUTHORIZED_NOTIFICATION_ACCESS: 'UNAUTHORIZED_NOTIFICATION_ACCESS',
  INVALID_NOTIFICATION_TYPE: 'INVALID_NOTIFICATION_TYPE',
  INVALID_CURSOR: 'INVALID_CURSOR',
  NOTIFICATION_ALREADY_ARCHIVED: 'NOTIFICATION_ALREADY_ARCHIVED',
  INVALID_PREFERENCE: 'INVALID_PREFERENCE',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export const NOTIFICATION_CONFIG = {
  DEFAULT_PAGE_LIMIT: 20,
  MAX_PAGE_LIMIT: 100,
  READ_RETENTION_DAYS: 180,
  DEFAULT_EXPIRY_DAYS: 90,
  BATCH_INSERT_CHUNK_SIZE: 500,
} as const;
